const MD = [
  {
    title: 'komatsu.co.id',
    type: 'Corporate Website · UI/UX · SEO',
    client: 'PT Komatsu Indonesia (via Tempo360)',
    desc: 'Corporate web platform centralized for heavy equipment products, after-sales services, industrial solutions, and digital marketing. Modular CMS supporting multi-department content management, SEO campaigns, and integration with CRM/ERP.',
    tech: ['ASP.NET', 'jQuery', 'IIS', 'SEO', 'UI/UX'],
    url: 'https://komatsu.co.id/',
  },
  {
    title: 'kencana.org',
    type: 'Enterprise ERP · Web System',
    client: 'PT Kencana Maju Bersama',
    desc: 'Internal web ERP managing 30+ business entities in one ecosystem. Centralized inventory, finance, operations, and administrative workflows. Real-time data management, RBAC, modular multi-entity architecture.',
    tech: ['Laravel', 'Vue.js', 'MySQL', 'REST API', 'RBAC'],
    url: 'https://kencana.org/',
  },
  {
    title: 'viva.kencana.org',
    type: 'Warehouse System · Web App',
    client: 'PT Kencana Maju Bersama',
    desc: 'Internal warehouse management system: stock opname digital, QR code generation & bulk PDF printing, multi-warehouse stock query, transfer transactions, and comprehensive inventory tracking.',
    tech: ['Laravel', 'Vue.js', 'MySQL', 'QR Code', 'PDF Export'],
    url: 'https://viva.kencana.org/',
  },
  {
    title: 'iPhone Gresik POS',
    type: 'POS System · Inventory · Web',
    client: 'iPhone Gresik Retail',
    desc: 'Web-based POS & inventory for iPhone retail. Product management with IMEI tracking, fast cashier transactions, daily/weekly/monthly reports, role-based access (Admin, Owner, Cashier, Staff), low-stock alerts.',
    tech: ['Laravel', 'MySQL', 'POS', 'RBAC', 'Reporting'],
    url: '',
  },
  {
    title: 'DAT Indonesia',
    type: 'E-Commerce · CMS · Web',
    client: 'DAT Audio Indonesia',
    desc: 'Premium CMS & e-commerce for DAT audio products. Multi-category catalog, real-time inventory, secure checkout, Raja Ongkir shipping, MidTrans payment gateway, warranty registration & service center locator.',
    tech: ['Laravel', 'MySQL', 'MidTrans', 'RajaOngkir', 'CMS'],
    url: 'https://datindonesia.co.id/',
  },
  {
    title: 'GAPULO',
    type: 'Tourism Web · Flutter App',
    client: 'Ministry of Tourism & Creative Economy RI',
    desc: "Digital information hub for Lombok gastronomy & culinary heritage. Built for the 'Thoughtful Indonesia' program. Interactive chatbot, cultural background, traditional recipes, restaurant listings, and village tourism guide.",
    tech: ['Flutter', 'GetX', 'Custom Views', 'Chatbot', 'HTTP API'],
    url: 'https://gapulo.netlify.app',
  },
  {
    title: 'All In One Phone',
    type: 'Management System · Web',
    client: 'Collaboration with Madhome',
    desc: 'Integrated web platform for mobile phone retail & repair shops. Service management with repair tracking, integrated POS, financial management (income/expense/P&L), inventory with low-stock alerts, and analytical dashboard.',
    tech: ['Laravel', 'REST API', 'MySQL', 'Chart.js', 'WebSocket'],
    url: 'https://allphone.store',
  },
  {
    title: 'CEGEH NGODING',
    type: 'SaaS · Code Generator · Web',
    client: 'Collaboration with Madhome',
    desc: 'Web-based Project & Code Generator SaaS to accelerate Laravel development. Auto-generates project structure, CRUD modules, API endpoints, controllers, models, services, and UI components based on user requirements.',
    tech: ['Laravel', 'Vue.js', 'SaaS', 'Code Gen', 'MySQL'],
    url: 'https://cng.devapps.my.id/',
  },
  {
    title: 'Friend Chart Clothing',
    type: 'ERP · E-Commerce · Web',
    client: 'Collaboration with Madhome',
    desc: 'Web platform for clothing brand operations: digital storefront, product catalog (categories, sizes, colors, variants), online sales with cart/checkout, inventory management, customer management, and admin dashboard.',
    tech: ['Laravel', 'MySQL', 'E-Commerce', 'Inventory', 'Chart.js'],
    url: 'http://friendartclothing.com/',
  },
  {
    title: 'Part Laptop Second',
    type: 'Management System · Web',
    client: 'Second-hand Laptop Parts Business',
    desc: 'Integrated system for laptop parts sales & repair: service management with repair tracking, POS & invoices, second-hand parts inventory with serial tracking, employee attendance, payroll, PKL student management, and financial reporting.',
    tech: ['Laravel', 'MySQL', 'POS', 'HR', 'Payroll'],
    url: 'http://partlaptopsecond.com/',
  },
  {
    title: 'Sinergi Gula Nusantara',
    type: 'Enterprise Platform · Web',
    client: 'SGN RUP — Multi-plant Operations',
    desc: 'Enterprise management platform for budgeting, financial planning, approval workflows, and operational management across multiple business units. Centralizes Capex/Opex budget, WBS, purchasing, material management, and approval processes.',
    tech: ['Laravel', 'Vue.js', 'MySQL', 'Enterprise', 'RBAC'],
    url: 'https://sirup.sinergigula.com/',
  },
  {
    title: 'DTMS Web',
    type: 'Transport Management · Enterprise',
    client: 'Petrokimia Gresik',
    desc: 'Digital Transport Management System for managing truck fleets. Multi-role platform (Control Tower, Helpdesk, Safety Officer, Vehicle Maintenance, Weigh Bridge). Real-time monitoring, operational dashboards, and financial reporting.',
    tech: ['Laravel', 'Vue.js', 'MySQL', 'Real-time', 'Multi-role'],
    url: 'https://dtms.petrokimia-gresik.com/',
  },
  {
    title: 'X3 Organizer',
    type: 'Landing Page · Tour & Travel',
    client: 'X3 Organizer',
    desc: 'Website landing page for tour and travel business. Features top destination exploration, tour packages, service showcase (Travel Guide, Ticket Booking, Hotel Booking), and competitive pricing display.',
    tech: ['Laravel', 'MySQL', 'Landing Page', 'Travel'],
    url: 'https://www.instagram.com/x3organizer/',
  },
  {
    title: 'Laracamp',
    type: 'E-Commerce · Online Course',
    client: 'Laracamp',
    desc: 'E-commerce platform for online programming courses. Features course catalog, mentoring programs, pricing comparison, student dashboard, bootcamp enrollment, and payment integration with Midtrans. Containerized with Docker.',
    tech: ['Laravel', 'MySQL', 'Midtrans', 'Docker', 'E-Learning'],
    url: '',
  },
  {
    title: 'Radja Kompor',
    type: 'Company Profile · E-Commerce',
    client: 'Radja Kompor',
    desc: 'Company profile and e-commerce website for gas stove specialist and second-hand gas stove trading. Features product showcase, service listing, documentation gallery, and contact/order form with map integration.',
    tech: ['Laravel', 'MySQL', 'Midtrans', 'Docker', 'E-Commerce'],
    url: '',
  },
  {
    title: 'SIPINBAR',
    type: 'Campus System · Web App',
    client: 'Politeknik Elektronika Negeri Surabaya',
    desc: 'Campus facility loan and equipment management system for PENS. Features equipment registration, loan requests with approval workflow, inventory tracking with serial numbers, data management, and PDF report generation.',
    tech: ['Laravel', 'MySQL', 'Campus System', 'PDF', 'Asset Management'],
    url: '',
  },
  {
    title: 'Posyandu Online',
    type: 'Health Monitoring · Web',
    client: 'Posyandu Digital',
    desc: 'Real-time Posyandu (maternal & child health) monitoring application. Allows health workers to record child growth data, immunization schedules, and health metrics digitally with dashboard for monitoring and reporting.',
    tech: ['Laravel', 'MySQL', 'Health', 'Real-time', 'Dashboard'],
    url: '',
  },
  {
    title: 'Viva Attendance',
    type: 'Mobile · HR · Face Recognition',
    client: 'PT Kencana Maju Bersama',
    desc: 'Mobile attendance app using face recognition technology. Supports geofencing (configurable per company entity), location-based check-in/out for office and field employees, real-time sync with remote APIs.',
    tech: ['Flutter', 'BLoC', 'Face Recognition', 'Geofencing', 'HTTP API'],
    url: 'https://android.kencana.org/',
  },
  {
    title: 'Viva Kencana Apps',
    type: 'Mobile · Super App · Enterprise',
    client: 'PT Kencana Maju Bersama',
    desc: 'Internal super app for 30+ business entities: stock opname via QR Code scanning, sales activity tracking, loading dock monitoring, PR/PO approval workflows, and real-time backend synchronization.',
    tech: ['Flutter', 'BLoC', 'QR Code', 'HTTP API', 'Multi-entity'],
    url: 'https://android.kencana.org/',
  },
  {
    title: 'Viva Kencana Ekspedisi',
    type: 'Mobile · Fleet Monitoring',
    client: 'PT Kencana Maju Bersama',
    desc: 'Fleet monitoring app for vehicle administrators. Real-time vehicle availability and operational status, advanced filter and local search, vehicle detail info, and status update confirmation for optimal fleet management.',
    tech: ['Flutter', 'BLoC', 'SharedPreferences', 'HTTP API', 'Fleet'],
    url: 'https://android.kencana.org/',
  },
  {
    title: 'Fasindo',
    type: 'Mobile · Super App · Property',
    client: 'Fasindo Property',
    desc: 'Comprehensive super app for property & construction: house model booking, interactive site map with GPS, cash advance/PO/PR/SPB approvals, finance management, SPK checklist, and field progress monitoring.',
    tech: ['Flutter', 'BLoC', 'flutter_map', 'Geolocator', 'HTTP API'],
    url: 'https://android.kencana.org/',
  },
  {
    title: 'TOBANG',
    type: 'Mobile · E-Commerce · Construction',
    client: 'TOBANG App',
    desc: 'E-commerce platform for construction materials with member and seller roles. Product management, sorting/searching, courier selection, Indodana payment, Firebase notifications, Google Maps tracking, and iOS support.',
    tech: ['Flutter', 'GetX', 'Firebase', 'Google Maps', 'Indodana'],
    url: 'https://play.google.com/store/apps/details?id=com.tobang.tobang_membership&hl=id',
  },
  {
    title: 'Fake Go-Send',
    type: 'Mobile · Delivery · OpenStreetMap',
    client: 'Personal Project',
    desc: 'Delivery app resembling Gojek. Integrates OpenStreetMap for location/address, item detail input (name, description, image), distance calculation between points, and offline delivery history via Sqflite local database.',
    tech: ['Flutter', 'GetX', 'OpenStreetMap', 'Sqflite', 'Geolocator'],
    url: '',
  },
  {
    title: 'Starlife',
    type: 'Mobile · Healthcare · Doctor Booking',
    client: 'Burningroom Technology',
    desc: 'Full doctor booking app built from scratch for production. Features: doctor search by specialty, schedule booking, patient profiles, family patient registration, medical records, appointment queue, and health news.',
    tech: ['Flutter', 'GetX', 'MidTrans', 'Dio', 'HTTP API'],
    url: '',
  },
  {
    title: 'SOFA App',
    type: 'Mobile · Store Management · POS',
    client: 'SOFA App',
    desc: 'Store management for Owner/Staff/Employee roles. Manages products, expenses, income with graphical reports (daily/weekly/monthly). Print-to-PDF, checkout with calculator, GraphQL API integration, and multi-store support.',
    tech: ['Flutter', 'GetX', 'GraphQL', 'Convert PDF', 'Printer'],
    url: '',
  },
  {
    title: 'Shoesmart',
    type: 'Mobile · E-Commerce · Footwear',
    client: 'Shoesmart',
    desc: 'E-commerce app for footwear (shoes, sandals, sneakers). Product browsing, cart management, online transactions, order tracking, promo vouchers, payment via MidTrans/BCA VA, responsive design for seamless experience.',
    tech: ['Flutter', 'GetX', 'MidTrans', 'Firebase FCM', 'Dio'],
    url: '',
  },
  {
    title: 'DTMS V2',
    type: 'Mobile · Fleet Management · Enterprise',
    client: 'Petrokimia Gresik',
    desc: "Multi-platform fleet management for Petrokimia Gresik's truck fleet. Real-time tracking, order management, vehicle maintenance checklist, weighbridge operations, offline mode with SQLite+API sync, OpenRouteMap navigation.",
    tech: ['Flutter', 'BLoC', 'gRPC', 'Sqflite', 'OpenRouteMap'],
    url: '',
  },
  {
    title: 'GUNMA',
    type: 'Mobile · Internship Info · Campus',
    client: 'Team Project',
    desc: 'Android app providing internship, job opportunities, and scholarship information for students. Browse by city/region, detailed program info (paid/WFH/WFO/Skill Training), upload internship, and notification settings.',
    tech: ['Flutter', 'GetX', 'Dio', 'SharedPreferences', 'HTTP API'],
    url: 'https://play.google.com/store/apps/details?id=com.gunmajoss.gunma&hl=id',
  },
  {
    title: 'Ambroise',
    type: 'Mobile · Barbershop · AR',
    client: 'Team Project',
    desc: 'Barbershop app with booking feature and virtual hairstyle preview using Augmented Reality (SparkAR SDK) and machine learning for hair recommendation. MVVM Clean Architecture, MidTrans & Xendit payment.',
    tech: ['Android Kotlin', 'MVVM', 'SparkAR', 'MidTrans', 'Retrofit'],
    url: '',
  },
  {
    title: 'PEDULY',
    type: 'Mobile · Crowdfunding · Social',
    client: 'Team Project',
    desc: 'Crowdfunding app for individuals to raise funds for those in need. Features campaign creation, donation management, BCA Virtual Account payment, donor tracking, fund utilization planning, and volunteer program.',
    tech: ['Flutter', 'Provider', 'MidTrans', 'SharedPreferences', 'HTTP API'],
    url: 'https://play.google.com/store/apps/details?id=com.peduly.pedulywebview',
  },
  {
    title: 'ONE EVENT',
    type: 'Mobile · Sports Booking',
    client: 'Team Project',
    desc: 'Sports field booking app with two roles (field owner and booker). Features field listing, schedule management, multi-location points, coach booking for training, tournament management, and MidTrans payment.',
    tech: ['Flutter', 'GetX', 'GraphQL', 'MidTrans', 'Dio'],
    url: '',
  },
  {
    title: 'DOCTUGO',
    type: 'Mobile · Doctor Booking',
    client: 'Trust Medis',
    desc: 'Doctor booking app built from scratch: login/register, homepage, doctor categories, doctor detail & availability, appointment scheduling, e-ticket with QR code, queue number system, and profile management.',
    tech: ['Flutter', 'GetX', 'Custom Views', 'Custom Widgets', 'Clean Architecture'],
    url: '',
  },
  {
    title: 'RESTOBOOKING',
    type: 'Mobile · Food Ordering',
    client: 'Personal Project',
    desc: 'Cake and snack ordering app built from scratch. Food item listing, detailed product view, checkout functionality, destination location selection, payment integration, and order history tracking. Built solo.',
    tech: ['Flutter', 'GetX', 'Custom Views', 'Custom Widgets', 'Maps'],
    url: '',
  },
  {
    title: 'KALPATARU',
    type: 'Mobile · Election Monitoring',
    client: 'Team Project',
    desc: 'Election result monitoring app for legislative (DPRD) and mayoral candidates. Input voting data per TPS (polling station), real-time vote tallying, provincial/district/sub-district filtering, and photo documentation.',
    tech: ['Flutter', 'GetX', 'Custom Widgets', 'HTTP API', 'SharedPreferences'],
    url: '',
  },
  {
    title: 'TAGBETA',
    type: 'Mobile · Community News',
    client: 'Team Project',
    desc: 'Community incident reporting app for real-time news submission. Users submit incidents with text, category, location (Geolocator), and photo evidence. Central hub processes and displays all reports publicly.',
    tech: ['Flutter', 'GetX', 'Google Maps', 'Geolocator', 'HTTP API'],
    url: '',
  },
  {
    title: 'PMovie',
    type: 'Mobile · Entertainment · Movies',
    client: 'Personal Project',
    desc: 'Entertainment companion app for movies and TV shows. In-depth film information, TV show details, search functionality, recommendations, rating display, and seamless exploration of cinematic content.',
    tech: ['Flutter', 'GetX', 'Custom Views', 'HTTP API', 'TMDB API'],
    url: '',
  },
  {
    title: 'You Agency',
    type: 'Mobile · Insurance · Prudential',
    client: 'Prudential Indonesia',
    desc: 'Agent app for Prudential insurance products. Provides detailed information about insurance packages (Asuransi Jiwa, PruCinta, PruAnugerah, Unit Link, Tradisional), career path (Junior/Senior/Supervisor), and product comparison to assist agents with client consultations.',
    tech: ['Flutter', 'GetX', 'Custom Views', 'HTTP API', 'Play Store'],
    url: '',
  },
  {
    title: 'komatsu.co.id Redesign',
    type: 'Catalog',
    client: '',
    desc: 'Corporate Website · SEO · UI/UX',
    tech: [],
    url: '',
  },
  {
    title: 'Kencana ERP System',
    type: 'Catalog',
    client: '',
    desc: 'Enterprise · 30+ Business Entities',
    tech: [],
    url: '',
  },
  {
    title: 'Viva Kencana Warehouse',
    type: 'Catalog',
    client: '',
    desc: 'Warehouse · QR Code · Stock Opname',
    tech: [],
    url: '',
  },
  {
    title: 'iPhone Gresik POS',
    type: 'Catalog',
    client: '',
    desc: 'Point of Sale · Inventory · Retail',
    tech: [],
    url: '',
  },
  {
    title: 'DAT Indonesia E-Commerce',
    type: 'Catalog',
    client: '',
    desc: 'Audio Products · MidTrans · RajaOngkir',
    tech: [],
    url: '',
  },
  {
    title: 'GAPULO Tourism Platform',
    type: 'Catalog',
    client: '',
    desc: 'Lombok Gastronomy · Ministry RI',
    tech: [],
    url: '',
  },
  {
    title: 'Cegeh Ngoding SaaS',
    type: 'Catalog',
    client: '',
    desc: 'Laravel Code Generator · Multi-framework',
    tech: [],
    url: '',
  },
  {
    title: 'Friend Chart Clothing ERP',
    type: 'Catalog',
    client: '',
    desc: 'Garment · ERP · E-Commerce',
    tech: [],
    url: '',
  },
  {
    title: 'Part Laptop Second System',
    type: 'Catalog',
    client: '',
    desc: 'Service · POS · HR · Payroll',
    tech: [],
    url: '',
  },
  {
    title: 'Viva Attendance',
    type: 'Catalog Mobile',
    client: '',
    desc: 'Face Recognition · Geofencing · Flutter',
    tech: [],
    url: '',
  },
  {
    title: 'Viva Kencana Apps',
    type: 'Catalog Mobile',
    client: '',
    desc: 'Super App · QR Code · Multi-entity',
    tech: [],
    url: '',
  },
  {
    title: 'Viva Kencana Ekspedisi',
    type: 'Catalog Mobile',
    client: '',
    desc: 'Fleet Monitoring · Real-time',
    tech: [],
    url: '',
  },
  {
    title: 'Fasindo Property',
    type: 'Catalog Mobile',
    client: '',
    desc: 'Super App · Site Map · Approval',
    tech: [],
    url: '',
  },
  {
    title: 'TOBANG E-Commerce',
    type: 'Catalog Mobile',
    client: '',
    desc: 'Construction Materials · Firebase',
    tech: [],
    url: '',
  },
  {
    title: 'Fake Go-Send Delivery',
    type: 'Catalog Mobile',
    client: '',
    desc: 'OpenStreetMap · Sqflite · GetX',
    tech: [],
    url: '',
  },
  {
    title: 'Starlife Doctor Booking',
    type: 'Catalog Mobile',
    client: '',
    desc: 'Healthcare · MidTrans · GetX',
    tech: [],
    url: '',
  },
  {
    title: 'SOFA Store Management',
    type: 'Catalog Mobile',
    client: '',
    desc: 'POS · GraphQL · PDF Print',
    tech: [],
    url: '',
  },
  {
    title: 'Shoesmart E-Commerce',
    type: 'Catalog Mobile',
    client: '',
    desc: 'Footwear · MidTrans · GetX',
    tech: [],
    url: '',
  },
  {
    title: 'DTMS V2 Fleet',
    type: 'Catalog Mobile',
    client: '',
    desc: 'Petrokimia Gresik · BLoC · gRPC',
    tech: [],
    url: '',
  },
  {
    title: 'GUNMA Internship App',
    type: 'Catalog Mobile',
    client: '',
    desc: 'Campus · Scholarships · Flutter',
    tech: [],
    url: '',
  },
  {
    title: 'Ambroise Barbershop',
    type: 'Catalog Mobile',
    client: '',
    desc: 'AR Hairstyle · Kotlin · MVVM',
    tech: [],
    url: '',
  },
  {
    title: 'PEDULY Crowdfunding',
    type: 'Catalog Mobile',
    client: '',
    desc: 'Social Impact · MidTrans · Flutter',
    tech: [],
    url: '',
  },
  {
    title: 'ONE EVENT Sports',
    type: 'Catalog Mobile',
    client: '',
    desc: 'Field Booking · Tournament · GetX',
    tech: [],
    url: '',
  },
  {
    title: 'DOCTUGO Doctor App',
    type: 'Catalog Mobile',
    client: '',
    desc: 'Booking · Queue System · Flutter',
    tech: [],
    url: '',
  },
  {
    title: 'KALPATARU Election',
    type: 'Catalog Mobile',
    client: '',
    desc: 'TPS Monitoring · Real-time Votes',
    tech: [],
    url: '',
  },
  {
    title: 'TAGBETA Community',
    type: 'Catalog Mobile',
    client: '',
    desc: 'Incident Reporting · Google Maps',
    tech: [],
    url: '',
  },
  {
    title: 'NCDB (National Cancer Database)',
    type: 'Healthcare Data System · Cancer Registry',
    client: '',
    desc: 'A cancer registry and data management platform built to record, manage, and report oncology patient data in line with international cancer registry standards. Structured data entry for patient demographics, tumor characteristics, staging, and treatment, with built-in validation for data quality and compliance. Key features include standardized coding for tumor topography and morphology (ICD-O-3), cancer staging support (AJCC TNM 8th Edition), role-based access control, and secure handling of sensitive patient records, following NAACCR and STORE (ACS) technical guidelines.',
    tech: ['Express.js', 'React', 'shadcn/ui', 'REST API'],
    url: 'https://oncoregistry.com',
  },
  {
    title: 'Cantik Glowing',
    type: 'Beauty Salon Website · Booking',
    client: '',
    desc: 'A business website developed for GlowUp Beauty Salon, a premium beauty salon in Menteng, Central Jakarta. The website serves as a digital storefront showcasing hair treatment, nail art, skincare, and makeup services, guiding visitors from browsing to booking appointments online. Core sections include a service catalog, before-and-after transformation gallery, team profiles, appointment booking flow, and location/contact info, with social proof through client ratings (4.9 from 1,240 reviews).',
    tech: [],
    url: 'https://cantikglowing.netlify.app',
  },
  {
    title: 'Herbal Nusa',
    type: 'E-Commerce · Herbal Products',
    client: '',
    desc: 'herbalnusa.netlify.app is an e-commerce website built for HerbalNusa, a brand offering natural herbal health products sourced from ingredients across Indonesia. The website functions as an online store that lets customers browse, learn about, and purchase herbal products in one place. The platform was built with a modular, conversion-focused approach covering the shopping journey — from a categorized product catalog (health, beauty, stamina, and immunity) and best-seller highlights, to a shopping cart and checkout flow. It also integrates content marketing through a herbal articles/blog section and a WhatsApp-based consultation feature to support customer questions before purchase. Beyond selling products, the website is optimized for a responsive user experience (UX) across mobile and desktop devices and supports marketing needs such as SEO, trust-building elements (certification badges, customer ratings), and promotional campaigns like free-shipping thresholds. Its scalable architecture enables future development and integration with external systems such as payment gateways, shipping/logistics providers, and marketplace channels as the business grows.',
    tech: [],
    url: 'https://herbalnusa.netlify.app',
  },
  {
    title: 'Klinik Sehat',
    type: 'Healthcare Website · Appointment Booking',
    client: '',
    desc: 'A healthcare website developed for Klinik Sehat Bersama, a trusted medical clinic serving patients and families. The website functions as a digital front door for the clinic, presenting its medical services, specialist doctors, and appointment booking in one accessible place.',
    tech: ['REST API'],
    url: 'https://klinikindonesia.netlify.app',
  },
  {
    title: 'Sistem Bisnis',
    type: 'ERP · SME Management',
    client: '',
    desc: "An all-in-one ERP web application built to help Indonesian SMEs (UMKM) manage their operations from a single dashboard, bringing orders, products, customers, and finances together in one place. Built with a modular, role-based approach (Super Admin, Manager, Cashier/Staff), with real-time order and inventory management, integrated CRM, automated financial reporting and analytics, and a demo-account flow that lets new users explore the dashboard quickly before committing.",
    tech: [],
    url: 'https://sistembisnis.netlify.app',
  },
  {
    title: 'Tokkoku',
    type: 'E-Commerce · Fashion',
    client: '',
    desc: "An e-commerce platform built to showcase and sell local Indonesian fashion, with a mission to support the country's SME (UMKM) fashion brands and local artisans. Covers the complete shopping journey — category-based product catalog (women, men, kids, batik, accessories, and shoes) and best-seller collections, to a shopping cart, wishlist, and personal account area — plus commerce essentials such as discount codes, free-shipping thresholds, a 30-day returns policy, and customer testimonials.",
    tech: [],
    url: 'https://tokkoku.netlify.app',
  },
  {
    title: 'Rumah Kita',
    type: 'Property Marketplace · Real Estate',
    client: '',
    desc: 'A property marketplace platform built to connect buyers, renters, sellers, and agents across Indonesia. Supports the full property-discovery journey — filtering by transaction type (buy or rent), property category (house, apartment, shop/ruko, villa, and kos), and location — to browsing featured listings and connecting with verified agents, plus a "Post an Ad" flow that lets owners and agents publish their own property listings.',
    tech: [],
    url: 'https://rumahmasakini.netlify.app',
  },
  {
    title: 'Belajar Smart',
    type: 'E-Learning Platform · Online Courses',
    client: '',
    desc: 'An online learning platform offering 500+ courses across web development, mobile app development, UI/UX design, data science, digital marketing, and foreign languages, delivered by 50+ experienced instructors. Features HD video lessons with 24/7 access, official certificates recognized by hundreds of companies, an active community forum of 120K+ learners, 1-on-1 mentoring sessions, lifetime access to purchased materials, and a 30-day money-back guarantee.',
    tech: [],
    url: 'https://belajarsmart.netlify.app',
  },
];
